### ISSUE TITLE
[🐛BUG] 您好，使用序列推荐模型中的TAGNN模型时报错 MAC环境下

### ISSUE THREAD

**Issue by w764567792** [RUCAIBox/RecBole-GNN#37]
Traceback (most recent call last):
  File "/Users/jason_wang/Desktop/RecBole-GNN-main/run_recbole_gnn.py", line 15, in <module>
    run_recbole_gnn(model=args.model, dataset=args.dataset, config_file_list=config_file_list)
  File "/Users/jason_wang/Desktop/RecBole-GNN-main/recbole_gnn/quick_start.py", line 33, in run_recbole_gnn
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "/Users/jason_wang/Desktop/RecBole-GNN-main/recbole_gnn/utils.py", line 115, in data_preparation
    dataloaders = load_split_dataloaders(config)
  File "/Users/jason_wang/Desktop/RecBole-master/recbole/data/utils.py", line 78, in load_split_dataloaders
    with open(saved_dataloaders_file, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not Config
(RecBole-master1) jason_wang@Jason-WangdeMBP RecBole-GNN-main % 

还请问是否有其他序列推荐可用的数据集，因为科研需求，想问下除了diginetica-not-merged数据集其他两个是否可用，谢谢！

**Comment by hyp1231** [comment]
您好，可以贴出运行指令吗？

**Comment by w764567792** [comment]
您好，运行指令如下
(RecBole-master1) jason_wang@Jason-WangdeMBP RecBole-GNN-main % python run_recbole_gnn.py -m TAGNN -d diginetica-not-merged

**Comment by hyp1231** [comment]
您好，建议将[本页面](https://github.com/RUCAIBox/RecBole-GNN/blob/main/results/sequential/diginetica.md) 中的配置文件保存至 `dig.yaml`，然后尝试运行
```bash
python run_recbole_gnn.py -m TAGNN -d diginetica-not-merged --config_files=dig.yaml
```

**Comment by w764567792** [comment]
非常感谢您的及时答复，但是我这样尝试以后还是报上面同样的错误，无论是把dig.yaml放在主目录或者quick_start_config目录下

**Comment by hyp1231** [comment]
> 非常感谢您的及时答复，但是我这样尝试以后还是报上面同样的错误，无论是把dig.yaml放在主目录或者quick_start_config目录下

您好，这个报错位置是 RecBole 主包中，好像是因为想要加载提前保存的 dataloaders，请问您有设置 dataloaders_save_path 这个参数吗？或者能否检查一下你 RecBole 项目的 recbole/data/utils.py 里面 `load_split_dataloaders` 这个函数是否有修改过吗？

RecBole 原实现：
https://github.com/RUCAIBox/RecBole/blob/fb9ee722bb1349db113af15b9bf6a14a2bccd0eb/recbole/data/utils.py#L91-L116

**Comment by w764567792** [comment]
非常感谢，已经解决，重新安装recbole后可以运行
